version: "3"
services:
    vmysql:
        image: mysql:5.7.22
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: vdbname
            MYSQL_USER: vdbuser
            MYSQL_PASSWORD: vdbpass
            MYSQL_ROOT_PASSWORD: vdbpassroot
        volumes:
         - db_data:/var/lib/mysql
    vapp:
        build: .
        ports:
            - 8080:8080
        environment:
            DB_HOST: vmysql:3306
            DB_USER: vdbuser
            DB_PASSWORD: vdbpass
            DB_NAME: vdbname
volumes:
    db_data: {}

